<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="9" failures="0" skipped="0" tests="9" time="1.724" timestamp="2021-06-02T14:29:31.695558" hostname="docker"><testcase classname="" name="service2.app" time="0.000"><error message="collection failure">venv/lib/python3.8/site-packages/_pytest/runner.py:311: in from_call
    result: Optional[TResult] = func()
venv/lib/python3.8/site-packages/_pytest/runner.py:341: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
venv/lib/python3.8/site-packages/_pytest/doctest.py:532: in collect
    module = import_path(self.fspath)
venv/lib/python3.8/site-packages/_pytest/pathlib.py:544: in import_path
    raise ImportPathMismatchError(module_name, module_file, path)
E   _pytest.pathlib.ImportPathMismatchError: ('app', '/home/JoshuaBrowne/Which-animal-am-I-Project/service1/app.py', PosixPath('/home/JoshuaBrowne/Which-animal-am-I-Project/service2/app.py'))</error></testcase><testcase classname="" name="service2.tests.test_service2" time="0.000"><error message="collection failure">/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1014: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:991: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:973: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named 'tests.test_service2'</error><error message="collection failure">ImportError while importing test module '/home/JoshuaBrowne/Which-animal-am-I-Project/service2/tests/test_service2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'tests.test_service2'</error></testcase><testcase classname="" name="service3.app" time="0.000"><error message="collection failure">venv/lib/python3.8/site-packages/_pytest/runner.py:311: in from_call
    result: Optional[TResult] = func()
venv/lib/python3.8/site-packages/_pytest/runner.py:341: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
venv/lib/python3.8/site-packages/_pytest/doctest.py:532: in collect
    module = import_path(self.fspath)
venv/lib/python3.8/site-packages/_pytest/pathlib.py:544: in import_path
    raise ImportPathMismatchError(module_name, module_file, path)
E   _pytest.pathlib.ImportPathMismatchError: ('app', '/home/JoshuaBrowne/Which-animal-am-I-Project/service1/app.py', PosixPath('/home/JoshuaBrowne/Which-animal-am-I-Project/service3/app.py'))</error></testcase><testcase classname="" name="service3.tests.test_service3" time="0.000"><error message="collection failure">/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1014: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:991: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:973: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named 'tests.test_service3'</error><error message="collection failure">ImportError while importing test module '/home/JoshuaBrowne/Which-animal-am-I-Project/service3/tests/test_service3.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'tests.test_service3'</error></testcase><testcase classname="" name="service4.app" time="0.000"><error message="collection failure">venv/lib/python3.8/site-packages/_pytest/runner.py:311: in from_call
    result: Optional[TResult] = func()
venv/lib/python3.8/site-packages/_pytest/runner.py:341: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
venv/lib/python3.8/site-packages/_pytest/doctest.py:532: in collect
    module = import_path(self.fspath)
venv/lib/python3.8/site-packages/_pytest/pathlib.py:544: in import_path
    raise ImportPathMismatchError(module_name, module_file, path)
E   _pytest.pathlib.ImportPathMismatchError: ('app', '/home/JoshuaBrowne/Which-animal-am-I-Project/service1/app.py', PosixPath('/home/JoshuaBrowne/Which-animal-am-I-Project/service4/app.py'))</error></testcase><testcase classname="" name="service4.tests.test_service4" time="0.000"><error message="collection failure">/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1014: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:991: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:973: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named 'tests.test_service4'</error><error message="collection failure">ImportError while importing test module '/home/JoshuaBrowne/Which-animal-am-I-Project/service4/tests/test_service4.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'tests.test_service4'</error></testcase></testsuite></testsuites>